---
name: build the docker image and deploy it on GCP
on:
  push:
    branches: [finding_all_URLs]
jobs:
  build_docker_image:
    name: build_docker_image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test
      PROJECT-ID: radiant-pilot-391309
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT-ID }}
        export_default_credentials: true
      
    - name: build docker image
      env:
        DOCKER_IMAGE: ${{ env.PROJECT-ID }}
      run: |-
        gcloud auth configure-docker australia-southeast1-docker.pkg.dev
        docker build -t australia-southeast1-docker.pkg.dev/radiant-pilot-391309/adscraper/nginx:latest .
        docker push australia-southeast1-docker.pkg.dev/radiant-pilot-391309/adscraper/nginx:latest 
    
    


